var TEST_MODELS = [
  {
    "id": 1,
    "name": "BP",
    "fullName": "Backpropagation",
    "year": 1986,
    "author": "David E. Rumelhart, Geoffrey E. Hinton, Ronald J. Williams",
    "organization": "University of California, San Diego",
    "category": "基础算法",
    "architecture": "多层感知机 (MLP)",
    "parameters": "视网络规模而定",
    "description": "反向传播算法是深度学习最基础的训练方法。它通过链式法则高效计算损失函数对各层权重的梯度，使得训练多层神经网络成为可能。虽然并非一个具体的\"模型\"，但它是几乎所有现代深度学习模型训练的基石。",
    "keyInnovation": "将误差信号从输出层逐层反向传播至输入层，利用链式法则高效计算梯度，解决了多层网络训练的梯度计算难题",
    "datasets": "XOR 等合成数据",
    "performance": "证明了多层网络可以学习非线性可分问题",
    "paperUrl": "https://www.nature.com/articles/323533a0",
    "codeUrl": "",
    "tags": ["反向传播", "梯度下降", "MLP", "基础算法"]
  },
  {
    "id": 2,
    "name": "LeNet-5",
    "fullName": "LeNet-5: Gradient-Based Learning Applied to Document Recognition",
    "year": 1998,
    "author": "Yann LeCun, Léon Bottou, Yoshua Bengio, Patrick Haffner",
    "organization": "AT&T Labs / Bell Labs",
    "category": "图像分类",
    "architecture": "CNN",
    "parameters": "约 60K",
    "description": "LeNet-5 是卷积神经网络的开山之作，由 Yann LeCun 提出，最初用于手写数字识别。它确立了卷积层+池化层+全连接层的基本架构范式，被美国银行广泛用于支票识别，是最早成功商用的深度学习模型之一。",
    "keyInnovation": "确立了卷积神经网络的基本架构：交替使用卷积层和下采样（池化）层，利用局部感受野和权值共享大幅减少参数量",
    "datasets": "MNIST",
    "performance": "MNIST 手写数字识别错误率 0.8%",
    "paperUrl": "https://yann.lecun.com/exdb/publis/pdf/lecun-01a.pdf",
    "codeUrl": "https://yann.lecun.com/exdb/lenet/",
    "tags": ["CNN", "手写识别", "MNIST", "开山之作"]
  },
  {
    "id": 3,
    "name": "AlexNet",
    "fullName": "ImageNet Classification with Deep Convolutional Neural Networks",
    "year": 2012,
    "author": "Alex Krizhevsky, Ilya Sutskever, Geoffrey E. Hinton",
    "organization": "University of Toronto",
    "category": "图像分类",
    "architecture": "CNN",
    "parameters": "约 60M",
    "description": "AlexNet 在 2012 年 ImageNet 竞赛（ILSVRC）中以巨大优势夺冠，将 Top-5 错误率从 26% 降至 15.3%，震惊了整个计算机视觉领域。它证明了深度 CNN + 大数据 + GPU 训练的强大组合，正式拉开了深度学习革命的序幕。",
    "keyInnovation": "首次在大规模图像识别中使用 ReLU 激活函数、Dropout 正则化、数据增强和 GPU 并行训练；使用重叠池化（Overlapping Pooling）",
    "datasets": "ImageNet (1.2M 训练图像)",
    "performance": "ImageNet Top-5 错误率 15.3%（2012 ILSVRC 冠军）",
    "paperUrl": "https://papers.nips.cc/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html",
    "codeUrl": "https://github.com/pytorch/vision/blob/main/torchvision/models/alexnet.py",
    "tags": ["CNN", "ImageNet", "ReLU", "Dropout", "GPU训练"]
  },
  {
    "id": 4,
    "name": "ZFNet",
    "fullName": "Visualizing and Understanding Convolutional Networks",
    "year": 2013,
    "author": "Matthew D. Zeiler, Rob Fergus",
    "organization": "New York University",
    "category": "图像分类",
    "architecture": "CNN",
    "parameters": "约 65M",
    "description": "ZFNet 是 2013 年 ILSVRC 的冠军，通过对 AlexNet 进行细致的调整和改进而获得。其最大贡献在于提出了一种可视化卷积神经网络特征的方法——反卷积（Deconvolution），让人们首次能够\"看到\"网络每一层学到了什么。",
    "keyInnovation": "反卷积可视化（Deconvolutional Visualization），通过反池化、反激活和反卷积操作，将特征图映射回像素空间，揭示网络各层的特征表示",
    "datasets": "ImageNet",
    "performance": "ImageNet Top-5 错误率 11.2%（2013 ILSVRC 冠军）",
    "paperUrl": "https://arxiv.org/abs/1311.2901",
    "codeUrl": "",
    "tags": ["CNN", "ImageNet", "可视化", "反卷积"]
  },
  {
    "id": 5,
    "name": "VGGNet",
    "fullName": "Very Deep Convolutional Networks for Large-Scale Image Recognition",
    "year": 2014,
    "author": "Karen Simonyan, Andrew Zisserman",
    "organization": "University of Oxford",
    "category": "图像分类",
    "architecture": "CNN",
    "parameters": "138M (VGG-16) / 144M (VGG-19)",
    "description": "VGGNet 的核心思想是\"更深更好\"——通过堆叠多个 3×3 小卷积核来替代大卷积核，在保持相同感受野的同时减少参数量。VGG-16 和 VGG-19 因其简洁优雅的结构成为深度学习中最经典的骨干网络之一，至今仍被广泛用作特征提取器。",
    "keyInnovation": "使用连续的 3×3 小卷积核堆叠替代大卷积核（两个 3×3 等效于一个 5×5，三个 3×3 等效于一个 7×7），增加非线性表达能力同时减少参数",
    "datasets": "ImageNet",
    "performance": "ImageNet Top-5 错误率 7.3%（VGG-16）",
    "paperUrl": "https://arxiv.org/abs/1409.1556",
    "codeUrl": "https://github.com/pytorch/vision/blob/main/torchvision/models/vgg.py",
    "tags": ["CNN", "ImageNet", "深层网络", "3×3卷积"]
  },
  {
    "id": 6,
    "name": "GoogLeNet",
    "fullName": "Going Deeper with Convolutions",
    "year": 2014,
    "author": "Christian Szegedy et al.",
    "organization": "Google",
    "category": "图像分类",
    "architecture": "CNN (Inception)",
    "parameters": "约 6.8M (GoogLeNet v1)",
    "description": "GoogLeNet（也称 Inception v1）引入了 Inception 模块，通过并行使用不同大小的卷积核（1×1、3×3、5×5）和池化操作，让网络自适应地学习最优的特征组合。它以 22 层的深度和仅 6.8M 的参数量赢得了 2014 年 ILSVRC 冠军。",
    "keyInnovation": "Inception 模块——在相同层级并行使用多尺度卷积核（1×1、3×3、5×5），通过 1×1 卷积降维减少计算量；引入辅助分类器帮助梯度传播",
    "datasets": "ImageNet",
    "performance": "ImageNet Top-5 错误率 6.7%（2014 ILSVRC 冠军）",
    "paperUrl": "https://arxiv.org/abs/1409.4842",
    "codeUrl": "https://github.com/pytorch/vision/blob/main/torchvision/models/googlenet.py",
    "tags": ["CNN", "ImageNet", "Inception", "多尺度"]
  },
  {
    "id": 7,
    "name": "ResNet",
    "fullName": "Deep Residual Learning for Image Recognition",
    "year": 2015,
    "author": "Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun",
    "organization": "Microsoft Research",
    "category": "图像分类",
    "architecture": "CNN",
    "parameters": "25.6M (ResNet-50)",
    "description": "ResNet 通过引入残差连接（Skip Connection）解决了深度神经网络中的梯度消失问题，使得训练数百甚至上千层的网络成为可能。ResNet-152 在 2015 年 ILSVRC 中以 3.57% 的 Top-5 错误率超越人类水平（约 5.1%），是计算机视觉领域最具影响力的架构之一。",
    "keyInnovation": "残差学习框架（Residual Learning），使用快捷连接（Shortcut Connections）让网络学习残差映射 F(x) = H(x) - x 而非直接映射 H(x)，解决了深层网络的退化问题",
    "datasets": "ImageNet",
    "performance": "ImageNet Top-5 错误率 3.57%（ResNet-152，超越人类水平）",
    "paperUrl": "https://arxiv.org/abs/1512.03385",
    "codeUrl": "https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py",
    "tags": ["CNN", "残差连接", "ImageNet", "深层网络"]
  },
  {
    "id": 8,
    "name": "YOLO",
    "fullName": "You Only Look Once: Unified, Real-Time Object Detection",
    "year": 2016,
    "author": "Joseph Redmon, Santosh Divvala, Ross Girshick, Ali Farhadi",
    "organization": "University of Washington",
    "category": "目标检测",
    "architecture": "CNN",
    "parameters": "约 8.7M (YOLOv1)",
    "description": "YOLO 将目标检测重新构建为单一的回归问题，从图像像素直接预测边界框坐标和类别概率。它实现了端到端的实时目标检测，速度远超当时的两阶段检测器（如 Faster R-CNN），开创了单阶段检测器的先河。",
    "keyInnovation": "将目标检测视为回归问题，单次前向传播即可完成检测，实现实时推理；将图像划分为 S×S 网格，每个网格同时预测边界框和类别概率",
    "datasets": "PASCAL VOC / COCO",
    "performance": "PASCAL VOC mAP 63.4%，实时速度 45 FPS",
    "paperUrl": "https://arxiv.org/abs/1506.02640",
    "codeUrl": "https://github.com/pjreddie/darknet",
    "tags": ["目标检测", "实时检测", "CNN", "端到端"]
  },
  {
    "id": 9,
    "name": "DenseNet",
    "fullName": "Densely Connected Convolutional Networks",
    "year": 2017,
    "author": "Gao Huang, Zhuang Liu, Laurens van der Maaten, Kilian Q. Weinberger",
    "organization": "Cornell University / Facebook AI Research",
    "category": "图像分类",
    "architecture": "CNN",
    "parameters": "20M (DenseNet-121) / 27M (DenseNet-169)",
    "description": "DenseNet 提出了密集连接（Dense Connectivity）的思想：每一层都与前面所有层直接相连。这种设计极大地促进了特征复用和梯度传播，以更少的参数量达到了与 ResNet 相当甚至更好的性能，同时显著减少了过拟合。",
    "keyInnovation": "密集连接块（Dense Block）——每一层的输入是所有前面层的特征图的拼接（concatenation），实现了深层特征复用和高效的梯度传播",
    "datasets": "ImageNet / CIFAR",
    "performance": "ImageNet Top-1 错误率 22.5%（DenseNet-264），参数量仅为 ResNet 的一半左右",
    "paperUrl": "https://arxiv.org/abs/1608.06993",
    "codeUrl": "https://github.com/pytorch/vision/blob/main/torchvision/models/densenet.py",
    "tags": ["CNN", "ImageNet", "密集连接", "特征复用"]
  },
  {
    "id": 10,
    "name": "SENet",
    "fullName": "Squeeze-and-Excitation Networks",
    "year": 2017,
    "author": "Jie Hu, Li Shen, Gang Sun",
    "organization": "Momenta / Oxford University",
    "category": "图像分类",
    "architecture": "CNN + 注意力机制",
    "parameters": "约 28M (SE-ResNet-50)",
    "description": "SENet 引入了通道注意力机制（Squeeze-and-Excitation），通过自适应地重新校准通道特征响应，让网络学会关注更有用的特征通道。SENet 赢得了 2017 年 ILSVRC 冠军，其 SE 模块可以即插即用地嵌入到任何现有 CNN 架构中。",
    "keyInnovation": "Squeeze-and-Excitation 模块——通过全局平均池化（Squeeze）获取通道描述符，再通过全连接层（Excitation）学习各通道的重要性权重，实现自适应通道特征校准",
    "datasets": "ImageNet",
    "performance": "ImageNet Top-5 错误率 2.25%（SENet-154，2017 ILSVRC 冠军）",
    "paperUrl": "https://arxiv.org/abs/1709.01507",
    "codeUrl": "https://github.com/hujie-frank/SENet",
    "tags": ["CNN", "注意力机制", "ImageNet", "通道注意力"]
  },
  {
    "id": 11,
    "name": "MobileNetV1",
    "fullName": "MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications",
    "year": 2017,
    "author": "Andrew G. Howard et al.",
    "organization": "Google",
    "category": "图像分类",
    "architecture": "CNN (深度可分离卷积)",
    "parameters": "4.2M (MobileNetV1)",
    "description": "MobileNetV1 专为移动端和嵌入式设备设计，提出了深度可分离卷积（Depthwise Separable Convolution），将标准卷积分解为深度卷积和逐点卷积两步，大幅减少了计算量和参数量。它在保持较高精度的同时，实现了极快的推理速度。",
    "keyInnovation": "深度可分离卷积（Depthwise Separable Convolution）——将标准卷积分解为深度卷积（Depthwise，每个通道独立卷积）和逐点卷积（Pointwise，1×1 卷积跨通道混合），计算量减少约 8-9 倍",
    "datasets": "ImageNet",
    "performance": "ImageNet Top-1 准确率 70.6%，计算量仅 569M MACs",
    "paperUrl": "https://arxiv.org/abs/1704.04861",
    "codeUrl": "https://github.com/pytorch/vision/blob/main/torchvision/models/mobilenetv1.py",
    "tags": ["CNN", "移动端", "轻量级", "深度可分离卷积"]
  },
  {
    "id": 12,
    "name": "Transformer",
    "fullName": "Attention Is All You Need",
    "year": 2017,
    "author": "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Łukasz Kaiser, Illia Polosukhin",
    "organization": "Google Brain",
    "category": "自然语言处理",
    "architecture": "Transformer",
    "parameters": "65M (原始模型)",
    "description": "Transformer 完全基于自注意力机制（Self-Attention），摒弃了传统的 RNN 和 CNN 结构。它是 GPT、BERT、T5 等众多里程碑模型的基础架构，彻底改变了 NLP 领域，并逐渐扩展到计算机视觉、语音、多模态等各个领域。",
    "keyInnovation": "多头自注意力机制（Multi-Head Self-Attention）和位置编码（Positional Encoding），实现了高度并行化的序列建模，彻底摆脱了循环结构的限制",
    "datasets": "WMT 2014 英德翻译",
    "performance": "WMT 2014 英德翻译 BLEU 28.4，训练速度提升一个数量级",
    "paperUrl": "https://arxiv.org/abs/1706.03762",
    "codeUrl": "https://github.com/harvardnlp/annotated-transformer",
    "tags": ["注意力机制", "NLP", "机器翻译", "自注意力"]
  },
  {
    "id": 13,
    "name": "BERT",
    "fullName": "Bidirectional Encoder Representations from Transformers",
    "year": 2018,
    "author": "Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova",
    "organization": "Google AI Language",
    "category": "自然语言处理",
    "architecture": "Transformer Encoder",
    "parameters": "110M (BERT-Base) / 340M (BERT-Large)",
    "description": "BERT 通过双向预训练和掩码语言模型（MLM）任务，在 11 项 NLP 基准测试中刷新了纪录。它证明了\"预训练 + 微调\"范式的强大威力，开启了 NLP 的新时代，深刻影响了后续所有预训练语言模型的设计。",
    "keyInnovation": "双向预训练策略（掩码语言模型 MLM + 下一句预测 NSP），利用 Transformer Encoder 同时获取上下文信息，实现了深度的双向语言理解",
    "datasets": "BookCorpus + Wikipedia (16GB 文本)",
    "performance": "GLUE 基准测试 11 项任务 SOTA，SQuAD v1.1 F1 93.2",
    "paperUrl": "https://arxiv.org/abs/1810.04805",
    "codeUrl": "https://github.com/google-research/bert",
    "tags": ["预训练", "NLP", "双向编码", "微调", "MLM"]
  },
  {
    "id": 14,
    "name": "EfficientNet",
    "fullName": "EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks",
    "year": 2019,
    "author": "Mingxing Tan, Quoc V. Le",
    "organization": "Google Brain",
    "category": "图像分类",
    "architecture": "CNN (复合缩放)",
    "parameters": "5.3M (B0) ~ 66M (B7)",
    "description": "EfficientNet 提出了复合缩放（Compound Scaling）方法，统一地缩放网络的深度、宽度和分辨率。通过神经架构搜索（NAS）找到最优的基线网络，再通过复合缩放系数生成 B0-B7 一系列模型，在同等计算预算下显著超越了此前的所有 CNN。",
    "keyInnovation": "复合缩放方法（Compound Scaling）——使用一个统一的复合系数 φ 同时缩放网络深度、宽度和输入分辨率，而非独立调整单一维度",
    "datasets": "ImageNet",
    "performance": "ImageNet Top-1 准确率 84.4%（EfficientNet-B7），参数量仅 66M，比 GPipe 少 8.4 倍",
    "paperUrl": "https://arxiv.org/abs/1905.11946",
    "codeUrl": "https://github.com/pytorch/vision/blob/main/torchvision/models/efficientnet.py",
    "tags": ["CNN", "ImageNet", "模型缩放", "NAS", "高效"]
  },
  {
    "id": 15,
    "name": "ViT",
    "fullName": "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale",
    "year": 2020,
    "author": "Alexey Dosovitskiy, Lucas Beyer, Alexander Kolesnikov, Dirk Weissenborn, Xiaohua Zhai, Thomas Unterthiner, Mostafa Dehghani, Matthias Minderer, Georg Heigold, Sylvain Gelly, Jakob Uszkoreit, Neil Houlsby",
    "organization": "Google Research",
    "category": "图像分类",
    "architecture": "Vision Transformer (ViT)",
    "parameters": "86M (ViT-Base) / 307M (ViT-Large) / 632M (ViT-Huge)",
    "description": "Vision Transformer（ViT）将 Transformer 架构直接应用于图像分类任务，将图像分割为固定大小的 patch 序列，像处理文本 token 一样处理图像。在大规模数据集上预训练后，ViT 达到了超越经典 CNN 的性能，证明了 Transformer 在视觉领域的巨大潜力。",
    "keyInnovation": "将图像分割为 16×16 的 patch 并线性嵌入为序列，直接使用标准 Transformer Encoder 处理；证明了在大规模数据（JFT-300M）上预训练的纯 Transformer 可以超越 CNN",
    "datasets": "ImageNet / JFT-300M (预训练)",
    "performance": "ImageNet Top-1 准确率 88.55%（ViT-Huge，在 JFT-300M 预训练后）",
    "paperUrl": "https://arxiv.org/abs/2010.11929",
    "codeUrl": "https://github.com/google-research/vision_transformer",
    "tags": ["Transformer", "Vision", "ImageNet", "Patch", "预训练"]
  },
  {
    "id": 16,
    "name": "Stable Diffusion",
    "fullName": "High-Resolution Image Synthesis with Latent Diffusion Models",
    "year": 2022,
    "author": "Robin Rombach, Andreas Blattmann, Dominik Lorenz, Patrick Esser, Björn Ommer",
    "organization": "Stability AI / LMU Munich / Runway",
    "category": "图像生成",
    "architecture": "Latent Diffusion Model (U-Net + CLIP)",
    "parameters": "860M (U-Net) + 123M (CLIP Text Encoder)",
    "description": "Stable Diffusion 在潜在空间（Latent Space）中进行扩散过程，大幅降低了计算成本。它是目前最流行的开源文本到图像生成模型，催生了庞大的 AI 艺术创作社区，推动了生成式 AI 的民主化进程。",
    "keyInnovation": "在压缩的潜在空间而非像素空间进行扩散，大幅降低计算需求（比像素空间扩散快数十倍）；结合 CLIP 文本编码器实现高质量文本引导生成",
    "datasets": "LAION-5B",
    "performance": "FID 3.6（COCO 验证集），可生成高质量 512×512 图像",
    "paperUrl": "https://arxiv.org/abs/2112.10752",
    "codeUrl": "https://github.com/CompVis/stable-diffusion",
    "tags": ["扩散模型", "图像生成", "文本到图像", "开源", "潜在空间"]
  },
  {
    "id": 17,
    "name": "ConvNeXt",
    "fullName": "A ConvNet for the 2020s",
    "year": 2022,
    "author": "Zhuang Liu, Hanzi Mao, Chao-Yuan Wu, Christoph Feichtenhofer, Trevor Darrell, Saining Xie",
    "organization": "Meta AI (FAIR)",
    "category": "图像分类",
    "architecture": "纯 CNN (现代化设计)",
    "parameters": "89M (ConvNeXt-Base) / 350M (ConvNeXt-XLarge)",
    "description": "ConvNeXt 证明了纯 CNN 架构经过现代化设计改进后，仍然可以与 Transformer 模型（如 Swin Transformer）相媲美。它借鉴了 Transformer 的设计理念（如大卷积核、LayerNorm、GELU 激活等）来改进标准 ResNet，在精度和效率上都取得了优异表现。",
    "keyInnovation": "将 Transformer 的先进设计理念引入 CNN：使用 7×7 大卷积核替代 3×3、用 LayerNorm 替代 BatchNorm、用 GELU 替代 ReLU、减少激活和归一化层、调整下采样策略等",
    "datasets": "ImageNet-1K / ImageNet-22K",
    "performance": "ImageNet Top-1 准确率 87.8%（ConvNeXt-XL，ImageNet-22K 预训练），与 Swin Transformer 持平",
    "paperUrl": "https://arxiv.org/abs/2201.03545",
    "codeUrl": "https://github.com/facebookresearch/ConvNeXt",
    "tags": ["CNN", "ImageNet", "现代化", "大卷积核", "纯CNN"]
  },
  {
    "id": 18,
    "name": "GPT-4",
    "fullName": "GPT-4 Technical Report",
    "year": 2023,
    "author": "OpenAI",
    "organization": "OpenAI",
    "category": "大语言模型",
    "architecture": "Transformer Decoder (MoE)",
    "parameters": "未公开（估计超过 1.76 万亿，MoE 架构）",
    "description": "GPT-4 是 OpenAI 的旗舰多模态大语言模型，能够处理文本和图像输入，在各类专业和学术基准测试中达到人类水平的表现。它展现了强大的推理、编程、数学和创作能力，是目前最强大的通用 AI 模型之一。",
    "keyInnovation": "大规模多模态训练、RLHF 人类反馈强化学习、涌现能力（Emergent Abilities）、推测采用混合专家（MoE）架构实现高效推理",
    "datasets": "大规模互联网文本 + 图像数据（具体未公开）",
    "performance": "律师资格考试前 10%、SAT 数学 89%、多项基准测试达到人类水平",
    "paperUrl": "https://arxiv.org/abs/2303.08774",
    "codeUrl": "",
    "tags": ["大语言模型", "多模态", "RLHF", "生成式AI", "MoE"]
  },
  {
    "id": 19,
    "name": "YOLOv8",
    "fullName": "YOLOv8: Ultralytics YOLO Version 8",
    "year": 2023,
    "author": "Glenn Jocher, Ultralytics",
    "organization": "Ultralytics",
    "category": "目标检测",
    "architecture": "CNN (YOLO)",
    "parameters": "约 25.5M (YOLOv8-L)",
    "description": "YOLOv8 是 Ultralytics 推出的最新一代 YOLO 目标检测模型，采用 C2f 模块替代了 YOLOv5 中的 C3 模块，引入了更高效的特征融合网络（FPN+PAN），支持 Anchor-Free 检测头，在 COCO 数据集上达到了当时最先进的检测精度和速度。",
    "keyInnovation": "C2f 模块（Cross Stage Partial Bottleneck with 2 convolutions）提供更丰富的梯度流；Anchor-Free 解耦头简化了检测流程；FPN+PAN 双向特征金字塔实现多尺度特征融合",
    "datasets": "COCO, Pascal VOC, Open Images",
    "performance": "YOLOv8-L: mAP@50-95=52.9, FPS≈80 (T4 GPU)",
    "paperUrl": "https://github.com/ultralytics/ultralytics",
    "codeUrl": "https://github.com/ultralytics/ultralytics",
    "tags": ["目标检测", "YOLO", "实时检测", "Anchor-Free", "C2f", "FPN", "PAN"]
  },
  {
    "id": 20,
    "name": "Faster R-CNN",
    "fullName": "Faster R-CNN: Towards Real-Time Object Detection with Region Proposal Networks",
    "year": 2015,
    "author": "Shaoqing Ren, Kaiming He, Ross Girshick, Jian Sun",
    "organization": "Microsoft Research",
    "category": "目标检测",
    "architecture": "CNN + RPN",
    "parameters": "约 137M (ResNet-50 backbone)",
    "description": "Faster R-CNN 是目标检测领域的里程碑工作，首次将区域提议网络（RPN）与检测网络整合为统一的端到端架构。RPN 通过共享卷积特征实时生成高质量候选框，将检测速度从 Fast R-CNN 的 0.5 FPS 提升至 5 FPS，同时保持甚至提升检测精度。",
    "keyInnovation": "区域提议网络（Region Proposal Network, RPN）——与检测网络共享卷积特征，通过滑动窗口和锚框机制实时生成多尺度候选区域，实现端到端联合训练",
    "datasets": "PASCAL VOC 2007/2012, MS COCO",
    "performance": "PASCAL VOC 2007 mAP 73.2%, COCO mAP@0.5 42.7%, 检测速度 5 FPS (Titan X)",
    "paperUrl": "https://arxiv.org/abs/1506.01497",
    "codeUrl": "https://github.com/pytorch/vision/blob/main/torchvision/models/detection/faster_rcnn.py",
    "tags": ["目标检测", "RPN", "两阶段检测", "锚框", "实时检测"]
  },
  {
    "id": 21,
    "name": "Mask R-CNN",
    "fullName": "Mask R-CNN",
    "year": 2017,
    "author": "Kaiming He, Georgia Gkioxari, Piotr Dollár, Ross Girshick",
    "organization": "Facebook AI Research (FAIR)",
    "category": "目标检测",
    "architecture": "CNN + FPN + Mask Head",
    "parameters": "约 44M (ResNet-50-FPN)",
    "description": "Mask R-CNN 在 Faster R-CNN 基础上增加了第三个并行分支用于预测目标掩码，实现了目标检测与实例分割的统一。通过引入 RoI Align 解决 RoI Pooling 的量化误差问题，Mask R-CNN 在 COCO 实例分割任务上取得了当时最优结果，并成为实例分割的标准基线。",
    "keyInnovation": "RoI Align——使用双线性插值替代量化操作，消除 RoI Pooling 引入的像素级错位；并行掩码预测分支采用全卷积网络，保持空间分辨率，实现像素级实例分割",
    "datasets": "MS COCO",
    "performance": "COCO 实例分割 mAP 37.1%, 目标检测 mAP@0.5 59.8%, 超越当时所有单模型方法",
    "paperUrl": "https://arxiv.org/abs/1703.06870",
    "codeUrl": "https://github.com/facebookresearch/Detectron",
    "tags": ["实例分割", "目标检测", "RoI Align", "FPN", "像素级分割"]
  },
  {
    "id": 22,
    "name": "SSD",
    "fullName": "SSD: Single Shot MultiBox Detector",
    "year": 2016,
    "author": "Wei Liu, Dragomir Anguelov, Dumitru Erhan, Christian Szegedy, Scott Reed, Cheng-Yang Fu, Alexander C. Berg",
    "organization": "University of North Carolina / Google / University of Michigan",
    "category": "目标检测",
    "architecture": "CNN (单阶段)",
    "parameters": "约 34M (SSD512-VGG16)",
    "description": "SSD 是单阶段目标检测器的开创性工作，摒弃了两阶段检测的候选框生成步骤，直接在多个尺度的特征图上预测目标类别和位置。通过在不同层使用不同尺度和长宽比的默认框（Default Boxes），SSD 在保持较高精度的同时实现了 46-59 FPS 的实时检测速度。",
    "keyInnovation": "多尺度特征图预测——在多个卷积层（不同分辨率）上并行预测，浅层特征图检测小目标，深层特征图检测大目标；使用不同长宽比的默认框覆盖多样化目标形状",
    "datasets": "PASCAL VOC, MS COCO",
    "performance": "PASCAL VOC 2007 mAP 76.8% (SSD512), COCO test-dev mAP@0.5 46.5%, 速度 46 FPS (SSD300)",
    "paperUrl": "https://arxiv.org/abs/1512.02325",
    "codeUrl": "https://github.com/weiliu89/caffe/tree/ssd",
    "tags": ["目标检测", "单阶段检测", "实时检测", "多尺度", "默认框"]
  },
  {
    "id": 23,
    "name": "RetinaNet",
    "fullName": "Focal Loss for Dense Object Detection",
    "year": 2017,
    "author": "Tsung-Yi Lin, Priya Goyal, Ross Girshick, Kaiming He, Piotr Dollár",
    "organization": "Facebook AI Research (FAIR)",
    "category": "目标检测",
    "architecture": "CNN + FPN (单阶段)",
    "parameters": "约 36M (ResNet-50-FPN)",
    "description": "RetinaNet 解决了单阶段检测器长期存在的类别不平衡问题（前景/背景样本比例悬殊）。通过提出 Focal Loss，降低易分类样本的权重，使模型聚焦于难分类样本，RetinaNet 首次证明单阶段检测器可以达到甚至超越两阶段检测器的精度。",
    "keyInnovation": "Focal Loss——在标准交叉熵损失上添加调节因子 (1-p)^γ，自动降低易分类样本（高置信度）的损失权重，将训练聚焦于难分类的稀疏样本，解决类别极端不平衡问题",
    "datasets": "MS COCO",
    "performance": "COCO test-dev mAP 39.1% (ResNet-101-FPN), 超越当时所有单阶段检测器，接近两阶段检测器精度",
    "paperUrl": "https://arxiv.org/abs/1708.02002",
    "codeUrl": "https://github.com/facebookresearch/detectron2",
    "tags": ["目标检测", "单阶段检测", "Focal Loss", "类别不平衡", "FPN"]
  },
  {
    "id": 24,
    "name": "FCN",
    "fullName": "Fully Convolutional Networks for Semantic Segmentation",
    "year": 2015,
    "author": "Jonathan Long, Evan Shelhamer, Trevor Darrell",
    "organization": "UC Berkeley",
    "category": "语义分割",
    "architecture": "CNN (全卷积)",
    "parameters": "约 134M (FCN-8s-VGG16)",
    "description": "FCN 是语义分割领域的奠基性工作，首次将分类网络改造为全卷积网络，实现端到端的像素级分类。通过引入转置卷积（反卷积）进行上采样，并创新性地提出跳跃连接融合不同层级的特征，FCN 在 PASCAL VOC 等分割基准上取得了突破性进展。",
    "keyInnovation": "全卷积架构——将全连接层替换为 1×1 卷积，使网络可接受任意尺寸输入并输出对应尺寸的分割图；跳跃连接融合深层语义特征和浅层位置特征，平衡分类准确性和定位精度",
    "datasets": "PASCAL VOC, NYUDv2, SIFT Flow",
    "performance": "PASCAL VOC 2012 mean IU 62.2% (FCN-8s), 相比此前方法提升约 20%",
    "paperUrl": "https://arxiv.org/abs/1411.4038",
    "codeUrl": "https://github.com/shelhamer/fcn.berkeleyvision.org",
    "tags": ["语义分割", "全卷积网络", "像素级分类", "转置卷积", "跳跃连接"]
  },
  {
    "id": 25,
    "name": "U-Net",
    "fullName": "U-Net: Convolutional Networks for Biomedical Image Segmentation",
    "year": 2015,
    "author": "Olaf Ronneberger, Philipp Fischer, Thomas Brox",
    "organization": "University of Freiburg",
    "category": "语义分割",
    "architecture": "CNN (Encoder-Decoder)",
    "parameters": "约 31M",
    "description": "U-Net 最初为生物医学图像分割设计，其对称的编码器-解码器结构和丰富的跳跃连接使其成为语义分割领域最具影响力的架构之一。即使在训练样本极少的情况下，U-Net 也能通过数据增强实现高精度分割，被广泛应用于医学影像分析、卫星图像处理等领域。",
    "keyInnovation": "对称 U 形结构——收缩路径（编码器）捕获上下文语义信息，扩张路径（解码器）恢复空间定位；密集跳跃连接将编码器特征直接传递至解码器，融合高低层特征，实现精确定位",
    "datasets": "ISBI 2012 EM Segmentation Challenge",
    "performance": "ISBI 2012 EM 分割挑战 IoU 92%, 平均 Hausdorff 距离 1.2 像素；在 30 张训练图像上超越此前基于滑动窗口的 CNN 方法",
    "paperUrl": "https://arxiv.org/abs/1505.04597",
    "codeUrl": "https://github.com/milesial/Pytorch-UNet",
    "tags": ["语义分割", "医学图像", "编码器-解码器", "跳跃连接", "小样本学习"]
  },
  {
    "id": 26,
    "name": "DeepLab v3+",
    "fullName": "Encoder-Decoder with Atrous Separable Convolution for Semantic Image Segmentation",
    "year": 2018,
    "author": "Liang-Chieh Chen, Yukun Zhu, George Papandreou, Florian Schroff, Hartwig Adam",
    "organization": "Google",
    "category": "语义分割",
    "architecture": "CNN (Encoder-Decoder + ASPP)",
    "parameters": "约 43M (Xception-65 backbone)",
    "description": "DeepLab v3+ 结合了空间金字塔池化（ASPP）和编码器-解码器结构，通过空洞可分离卷积在保持较大感受野的同时减少计算量。作为 DeepLab 系列的集大成者，v3+ 在 PASCAL VOC 和 Cityscapes 等分割基准上取得了当时最优性能，成为语义分割的标准方法之一。",
    "keyInnovation": "空洞空间金字塔池化（ASPP）——使用不同扩张率的空洞卷积捕获多尺度上下文；编码器-解码器结构逐步恢复空间分辨率；深度可分离空洞卷积大幅减少参数量和计算量",
    "datasets": "PASCAL VOC 2012, Cityscapes",
    "performance": "PASCAL VOC 2012 test set mIOU 89.0% (Xception-71, 多尺度推理), Cityscapes test set mIOU 82.1%",
    "paperUrl": "https://arxiv.org/abs/1802.02611",
    "codeUrl": "https://github.com/tensorflow/models/tree/master/research/deeplab",
    "tags": ["语义分割", "ASPP", "空洞卷积", "编码器-解码器", "多尺度"]
  },
  {
    "id": 27,
    "name": "LSTM",
    "fullName": "Long Short-Term Memory",
    "year": 1997,
    "author": "Sepp Hochreiter, Jürgen Schmidhuber",
    "organization": "Technische Universität München",
    "category": "自然语言处理",
    "architecture": "RNN (LSTM)",
    "parameters": "视网络规模而定",
    "description": "LSTM 通过引入门控机制（输入门、遗忘门、输出门）和细胞状态，解决了传统 RNN 的长期依赖问题。作为序列建模的里程碑，LSTM 在语音识别、机器翻译、文本生成等任务上统治了近20年，直到 Transformer 的出现才逐渐被取代。",
    "keyInnovation": "门控机制和细胞状态——遗忘门决定保留多少历史信息，输入门控制新信息的写入，输出门调节输出的信息量；细胞状态作为长期记忆通道，梯度可无损传播，解决梯度消失/爆炸问题",
    "datasets": "TIMIT (语音), WMT (翻译), 各类文本语料",
    "performance": "TIMIT 语音识别 CTC 错误率 17.7% (2013), WMT'14 英法翻译 BLEU 34.8 (2014), 长期依赖任务上显著优于标准 RNN",
    "paperUrl": "https://www.bioinf.jku.at/publications/older/2604.pdf",
    "codeUrl": "https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html",
    "tags": ["序列建模", "RNN", "长短期记忆", "门控机制", "长期依赖"]
  },
  {
    "id": 28,
    "name": "GRU",
    "fullName": "Learning Phrase Representations using RNN Encoder-Decoder for Statistical Machine Translation",
    "year": 2014,
    "author": "Kyunghyun Cho, Bart van Merriënboer, Caglar Gulcehre, Dzmitry Bahdanau, Fethi Bougares, Holger Schwenk, Yoshua Bengio",
    "organization": "University of Montreal",
    "category": "自然语言处理",
    "architecture": "RNN (GRU)",
    "parameters": "视网络规模而定",
    "description": "GRU 是 LSTM 的简化变体，将输入门和遗忘门合并为更新门，并融合细胞状态和隐藏状态。相比 LSTM，GRU 参数量更少、计算更高效，在许多任务上能达到相当甚至更优的性能，成为资源受限场景下的首选序列模型。",
    "keyInnovation": "门控循环单元——更新门控制前一时刻隐藏状态的保留比例，重置门决定忽略多少历史信息；相比 LSTM 减少一个门和一个状态，结构更简洁，参数量减少约 25%，训练速度更快",
    "datasets": "WMT'14 英法翻译, 各类序列建模任务",
    "performance": "WMT'14 英法翻译 BLEU 34.5 (接近 LSTM 的 34.8), 训练速度提升约 20-30%, 参数量减少约 25%",
    "paperUrl": "https://arxiv.org/abs/1406.1078",
    "codeUrl": "https://pytorch.org/docs/stable/generated/torch.nn.GRU.html",
    "tags": ["序列建模", "RNN", "门控循环单元", "LSTM变体", "高效"]
  },
  {
    "id": 29,
    "name": "GPT-2",
    "fullName": "Language Models are Unsupervised Multitask Learners",
    "year": 2019,
    "author": "Alec Radford, Jeffrey Wu, Rewon Child, David Luan, Dario Amodei, Ilya Sutskever",
    "organization": "OpenAI",
    "category": "自然语言处理",
    "architecture": "Transformer Decoder",
    "parameters": "117M (Small) / 345M (Medium) / 762M (Large) / 1.5B (XL)",
    "description": "GPT-2 证明了大规模语言模型无需微调即可在多种 NLP 任务上取得优异表现，展现了强大的零样本（zero-shot）和少样本（few-shot）学习能力。由于担心滥用风险，OpenAI 最初选择分阶段发布模型，引发了关于 AI 伦理和模型发布的广泛讨论。",
    "keyInnovation": "无监督多任务学习——通过大规模语料预训练，模型自动学习多种 NLP 任务的模式；采用字节对编码（BPE）处理任意 Unicode 文本，实现真正的多语言、多领域通用语言模型",
    "datasets": "WebText (800万网页, 40GB 文本)",
    "performance": "LAMBADA 语言建模准确率 63.24%, COCO 图像描述 BLEU 11.5 (零样本), 在 8/9 个语言建模数据集上达到 SOTA",
    "paperUrl": "https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf",
    "codeUrl": "https://github.com/openai/gpt-2",
    "tags": ["预训练语言模型", "Transformer", "零样本学习", "多任务", "GPT"]
  },
  {
    "id": 30,
    "name": "T5",
    "fullName": "Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer",
    "year": 2019,
    "author": "Colin Raffel, Noam Shazeer, Adam Roberts, Katherine Lee, Sharan Narang, Michael Matena, Yanqi Zhou, Wei Li, Peter J. Liu",
    "organization": "Google Research",
    "category": "自然语言处理",
    "architecture": "Transformer (Encoder-Decoder)",
    "parameters": "60M (Small) / 220M (Base) / 770M (Large) / 3B (3B) / 11B (11B)",
    "description": "T5 将所有 NLP 任务统一为文本到文本（Text-to-Text）的生成范式，无论是分类、翻译、摘要还是问答，都视为序列生成问题。通过系统性地探索迁移学习的各个维度（模型架构、预训练目标、数据集规模等），T5 建立了预训练语言模型的标准方法论。",
    "keyInnovation": "Text-to-Text 统一框架——将所有任务转换为输入文本→目标文本的生成问题；C4 数据集（Colossal Clean Crawled Corpus）——750GB 清洗后的网页文本；系统性的迁移学习研究，探索了模型规模、训练步数、架构选择等关键超参数",
    "datasets": "C4 (750GB 清洗网页文本), GLUE, SuperGLUE, SQuAD, CNN/DailyMail 等",
    "performance": "GLUE benchmark 89.7 (T5-11B), SuperGLUE 89.3, SQuAD 2.0 F1 91.2, 在多个基准上达到或接近 SOTA",
    "paperUrl": "https://arxiv.org/abs/1910.10683",
    "codeUrl": "https://github.com/google-research/text-to-text-transfer-transformer",
    "tags": ["预训练语言模型", "Transformer", "Text-to-Text", "迁移学习", "多任务"]
  },
  {
    "id": 31,
    "name": "YOLOv3",
    "fullName": "YOLOv3: An Incremental Improvement",
    "year": 2018,
    "author": "Joseph Redmon, Ali Farhadi",
    "organization": "University of Washington",
    "category": "目标检测",
    "architecture": "CNN (单阶段 Anchor-based)",
    "parameters": "约 62M (YOLOv3-608)",
    "description": "YOLOv3 是 YOLO 系列的里程碑版本，引入了特征金字塔网络（FPN）实现多尺度预测，每个尺度使用三个不同大小的锚框检测目标。Darknet-53 主干网络借鉴了残差思想，53层卷积网络提供了强大的特征提取能力。YOLOv3 首次实现了在 COCO 数据集上与两阶段检测器相当的精度，同时保持实时性。",
    "keyInnovation": "多尺度预测（Feature Pyramid Network）——在三个不同分辨率的特征图上预测（大/中/小目标），借鉴 FPN 思想；Darknet-53 主干网络使用残差连接增强特征提取能力；使用 Logistic 替代 Softmax 实现多标签分类",
    "datasets": "MS COCO, PASCAL VOC",
    "performance": "COCO mAP@0.5: 57.9%, mAP@0.5:0.95: 33.0%, 推理速度 35 FPS (Titan X)",
    "paperUrl": "https://arxiv.org/abs/1804.02767",
    "codeUrl": "https://github.com/ultralytics/yolov3",
    "tags": ["目标检测", "多尺度", "FPN", "Anchor", "Darknet"]
  },
  {
    "id": 32,
    "name": "YOLOv5",
    "fullName": "YOLOv5",
    "year": 2020,
    "author": "Glenn Jocher, Ultralytics",
    "organization": "Ultralytics",
    "category": "目标检测",
    "architecture": "CNN (单阶段 Anchor-based)",
    "parameters": "1.9M (YOLOv5n) ~ 128M (YOLOv5x)",
    "description": "YOLOv5 是 YOLO 系列最工程化的版本，在易用性、推理速度和精度之间取得了最佳平衡。引入了 CSP（Cross Stage Partial）骨干网络、Mosaic 数据增强、AutoAnchor 等技术。提供了从 nano 到 extra-large 的6个规模变体，覆盖从移动端到服务器端的各种部署场景，是目前工业应用最广泛的检测模型。",
    "keyInnovation": "CSP骨干网络——将特征图分为两部分，一部分经过卷积处理后与另一部分拼接，减少计算量的同时增强梯度流；Mosaic数据增强——将4张图片拼接为一张，增强模型对不同尺度和上下文的学习能力；提供 n/s/m/l/x 六种规模变体",
    "datasets": "MS COCO, PASCAL VOC, VisDrone",
    "performance": "COCO mAP@0.5:95 = 52.7% (YOLOv5m), mAP@0.5:95 = 56.8% (YOLOv5l), 推理速度 140 FPS (YOLOv5s, RTX 3090)",
    "paperUrl": "https://arxiv.org/abs/2007.13200",
    "codeUrl": "https://github.com/ultralytics/yolov5",
    "tags": ["目标检测", "CSP", "Mosaic", "Anchor-based", "工业应用"]
  },
  {
    "id": 33,
    "name": "Swin Transformer",
    "fullName": "Swin Transformer: Hierarchical Vision Transformer Using Shifted Windows",
    "year": 2021,
    "author": "Ze Liu, Yutong Lin, Yue Cao, Han Hu, Yixuan Wei, Zheng Zhang, Stephen Lin, Baining Guo",
    "organization": "Microsoft Research Asia",
    "category": "图像分类",
    "architecture": "Vision Transformer (层次化 Window Attention)",
    "parameters": "88M (Swin-B) / 197M (Swin-L)",
    "description": "Swin Transformer 提出了层次化（Hierarchical）Transformer 结构，通过滑动窗口自注意力机制（Shifted Windows）实现高效的局部注意力计算。这种设计使 Swin Transformer 能够像 CNN 一样生成多尺度特征图，非常适合目标检测和语义分割等密集预测任务，在多项视觉基准上刷新 SOTA。",
    "keyInnovation": "滑动窗口自注意力（Shifted Window Self-Attention）——将图像划分为不重叠的 window，每个 window 内部计算自注意力，相邻 window 之间通过滑动shift实现信息交互；层次化结构——通过 Patch Merging 逐步减少 token 数量，形成类似 CNN 的金字塔结构",
    "datasets": "ImageNet-1K, ImageNet-22K, COCO, ADE20K",
    "performance": "ImageNet Top-1 准确率 87.3% (Swin-B, ImageNet-1K), COCO box AP 58.7% (Swin-L), ADE20K mIoU 53.5% (Swin-L), ICCV 2021 最佳论文",
    "paperUrl": "https://arxiv.org/abs/2103.14030",
    "codeUrl": "https://github.com/microsoft/Swin-Transformer",
    "tags": ["Vision Transformer", "滑动窗口", "多尺度", "目标检测", "语义分割"]
  },
  {
    "id": 34,
    "name": "DeiT",
    "fullName": "Training Data-Efficient Image Transformers & Distillation Through Attention",
    "year": 2021,
    "author": "Hugo Touvron, Matthieu Cord, Matthijs Douze, Francisco Massa, Alexandre Sablayrolles, Hervé Jégou",
    "organization": "Facebook AI Research (FAIR)",
    "category": "图像分类",
    "architecture": "Vision Transformer (数据高效)",
    "parameters": "86M (DeiT-B) / 22M (DeiT-S)",
    "description": "DeiT 证明了 Transformer 在 ImageNet 上无需 JFT-300M 等大规模预训练数据也能达到 SOTA 性能。通过改进的训练策略（更强的正则化、数据增强）和知识蒸馏技术，DeiT 在单节点 8 GPU 上训练 3 天即可达到 83.1% 的 Top-1 准确率，大大降低了 Vision Transformer 的训练门槛。",
    "keyInnovation": "数据高效训练策略——使用更强的数据增强（CutMix/Mixup）、知识蒸馏（使用 CNN 作为教师网络）、更长的训练 schedule；令牌蒸馏（Distillation Token）——与 CLS Token 一起学习蒸馏信号，提升学生 Transformer 的性能",
    "datasets": "ImageNet-1K",
    "performance": "ImageNet Top-1 准确率 83.1% (DeiT-B, 无外部数据), 85.2% (DeiT-B +蒸馏), 训练时间仅需 3 天 (8 GPU)",
    "paperUrl": "https://arxiv.org/abs/2012.12877",
    "codeUrl": "https://github.com/facebookresearch/deit",
    "tags": ["Vision Transformer", "知识蒸馏", "数据高效", "ImageNet", "小样本训练"]
  },
  {
    "id": 35,
    "name": "CLIP",
    "fullName": "Learning Transferable Visual Models From Natural Language Supervision",
    "year": 2021,
    "author": "Alec Radford, Jong Wook Kim, Chris Hallacy, Aditya Ramesh, Gabriel Goh, Sandhini Agarwal, Girish Sastry, Amanda Askell, Pamela Mishkin, Jack Clark, Gretchen Krueger, Ilya Sutskever",
    "organization": "OpenAI",
    "category": "多模态",
    "architecture": "双塔模型 (ViT + Transformer Text Encoder)",
    "parameters": "86M (ViT-B/32) ~ 1.78B (ViT-g/14)",
    "description": "CLIP 首次实现了从自然语言监督中高效学习可迁移的视觉模型。通过大规模图像-文本对（400M对）进行对比学习训练，CLIP 实现了真正的零样本（Zero-shot）分类能力，在无需任何训练数据的情况下即可完成多样化的视觉识别任务，开创了视觉-语言预训练的新范式。",
    "keyInnovation": "对比语言-图像预训练（Contrastive Language-Image Pre-training）——将图像和文本编码到同一特征空间，通过对比损失学习配对的图像-文本更相似、不配对的更不相似；零样本迁移——无需在目标数据集上训练，只需提供类别名称文本描述即可完成分类",
    "datasets": "WIT (WebImageText, 4亿图像-文本对)",
    "performance": "ImageNet Zero-shot Top-1 准确率 76.2% (ViT-L/14), 超越同期监督学习 ResNet50，零样本能力可迁移至 OCR、动作识别、卫星图像等 30+ 任务",
    "paperUrl": "https://arxiv.org/abs/2103.00020",
    "codeUrl": "https://github.com/openai/CLIP",
    "tags": ["多模态", "对比学习", "零样本", "视觉-语言", "迁移学习"]
  }
];

// ============================================================
// 本地代码文件路径映射表
// 用于前端加载专业版/教程版代码文件
// ============================================================
var MODEL_CODE_FILES = {
  "BP": { paper: "backpropagation_paper.py", tutorial: "backpropagation_tutorial.py" },
  "LeNet-5": { paper: "lenet5_paper.py", tutorial: "lenet5_tutorial.py" },
  "AlexNet": { paper: "alexnet_paper.py", tutorial: "alexnet_tutorial.py" },
  "ZFNet": { paper: "zfnet_paper.py", tutorial: "zfnet_tutorial.py" },
  "VGGNet": { paper: "vgg16_paper.py", tutorial: "vgg16_tutorial.py" },
  "GoogLeNet": { paper: "googlenet_paper.py", tutorial: "googlenet_tutorial.py" },
  "ResNet": { paper: "resnet50_paper.py", tutorial: "resnet50_tutorial.py" },
  "YOLO": { paper: "yolov1_paper.py", tutorial: "yolov1_tutorial.py" },
  "DenseNet": { paper: "densenet121_paper.py", tutorial: "densenet121_tutorial.py" },
  "SENet": { paper: "senet_paper.py", tutorial: "senet_tutorial.py" },
  "MobileNetV1": { paper: "mobilenetv1_paper.py", tutorial: "mobilenetv1_tutorial.py" },
  "Transformer": { paper: "transformer_paper.py", tutorial: "transformer_tutorial.py" },
  "BERT": { paper: "bert_paper.py", tutorial: "bert_tutorial.py" },
  "EfficientNet": { paper: "efficientnetb0_paper.py", tutorial: "efficientnetb0_tutorial.py" },
  "ViT": { paper: "vit_paper.py", tutorial: "vit_tutorial.py" },
  "Stable Diffusion": { paper: "stable_diffusion_paper.py", tutorial: "stable_diffusion_tutorial.py" },
  "ConvNeXt": { paper: "convnext_tiny_paper.py", tutorial: "convnext_tiny_tutorial.py" },
  "GPT-4": { paper: "gpt4_paper.py", tutorial: "gpt4_tutorial.py" },
  "YOLOv8": { paper: "yolov8n_paper.py", tutorial: "yolov8n_tutorial.py" },
  "Faster R-CNN": { paper: "fasterrcnn_paper.py", tutorial: "fasterrcnn_tutorial.py" },
  "Mask R-CNN": { paper: "maskrcnn_paper.py", tutorial: "maskrcnn_tutorial.py" },
  "SSD": { paper: "ssd300_paper.py", tutorial: "ssd300_tutorial.py" },
  "RetinaNet": { paper: "retinanet_paper.py", tutorial: "retinanet_tutorial.py" },
  "FCN": { paper: "fcn8s_paper.py", tutorial: "fcn8s_tutorial.py" },
  "U-Net": { paper: "unet_paper.py", tutorial: "unet_tutorial.py" },
  "DeepLab v3+": { paper: "deeplabv3plus_paper.py", tutorial: "deeplabv3plus_tutorial.py" },
  "LSTM": { paper: "lstm_paper.py", tutorial: "lstm_tutorial.py" },
  "GRU": { paper: "gru_paper.py", tutorial: "gru_tutorial.py" },
  "GPT-2": { paper: "gpt2_paper.py", tutorial: "gpt2_tutorial.py" },
  "T5": { paper: "t5_paper.py", tutorial: "t5_tutorial.py" },
  "YOLOv3": { paper: "yolov3_paper.py", tutorial: "yolov3_tutorial.py" },
  "YOLOv5": { paper: "yolov5s_paper.py", tutorial: "yolov5s_tutorial.py" },
  "Swin Transformer": { paper: "swin_tiny_paper.py", tutorial: "swin_tiny_tutorial.py" },
  "DeiT": { paper: "deit_paper.py", tutorial: "deit_tutorial.py" },
  "CLIP": { paper: "clip_paper.py", tutorial: "clip_tutorial.py" }
};
